1Password/shell-plugins

- README.md
For some browsers, the WEBP image with a .gif extension would not display  correctly, probably because the content type was guessed incorrectly.
By replacing the image with one that has the .webp extension, this problem  should be resolved.
> Fix extension of WEBP variant of usage example

- sdk/rpc/proto/protocol.go
- sdk/rpc/server/server.go
There are a few problems with how the `Provisioner` field of the `CredentialUsage` struct is currently exposed for locally built plugins:
- The `Executable` field of `ProvisionerID` is a pointer, which means it has a different value for each invocation of a plugin. This is especially problematic because `ProvisionerID` is used as the key of a map.
- `ProvisionerID` contains an unused `Plugin` field.
- `Credential` in `ProvisionerID` is not guaranteed to be unique.
- The `Provisioner` field of `CredentialUsage` is not set to `nil` before transferring it over RPC.
- Whether or not the `Provisioner` field is set is not encoded in `proto.GetPluginResponse`. This
This all combined led to plugins using this field panicking on startup and the `Provision` field not being accessible by the CLI.
To …
> Fix use of CredentialUsage.Provisioner for locally built plugins

- sdk/schema/credential_type.go
It'll be possible that a credential consists of all possible types of characters. The validation should report an error if none is allowed instead.
> Fix charset validation for `ValueComposition`

- cmd/contrib/main.go
In `make new-plugin`, instead of always using the last word of the credential name as the field name, also take the second to last word if the resulting field name is not too lengthy.
For example:
```
"Personal Access Token" => "Token"
"Secret Key" => "Key"
"API Key" => "API Key"
"Personal API Token" => "Token"
```
The 7 value is arbitrary and can be changed later if we feel like it.
This new field name is also used as the env var name:
Previously, we'd derive `GITHUB_PERSONAL_ACCESS_TOKEN`, but now it would be `GITHUB_TOKEN`.
> Derive field name in make new-plugin more intelligently

- cmd/contrib/main.go
- sdk/importer/file_importer.go
- sdk/provisioner.go
- sdk/rpc/server/plugin.go
Since we now use an up to date version of `go` consistently across all the closed-source code, using `interface{}` instead of `any` should not be a problem anymore.
> Revert "Revert using any instead of interface{}"

- plugins/datadog/api_key.go
- plugins/datadog/api_key_test.go
- plugins/datadog/test-fixtures/.dogrc
This PR adds `datadog` config file importer.
The config file location is `~/.dogrc`
> datadog config file importer

- plugins/lacework/api_key.go
- plugins/lacework/api_key_test.go
- plugins/lacework/lacework.go
- plugins/lacework/plugin.go
- plugins/lacework/test-fixtures/lacework.toml
- sdk/schema/fieldname/names.go
Adds support for the [Lacework CLI](https://docs.lacework.com/cli/), including import from the config file produced by `lacework configure`.
```
➜  shell-plugins git:(lacework) make lacework/validate
go run cmd/contrib/main.go lacework/validate
✔ Has plugin name set
✔ Plugin name only using lowercase characters or digits
✔ Plugin name not longer than 20 characters
✔ Has platform name set
✔ Has platform homepage URL set
✔ Has a credential type or executable defined
✔ Has no more than one credential type defined. Plugins with multiple credential types are not supported yet
✔ Has no more than one executable defined. Plugins with multiple executables are not supported yet
✔ Has name set
✔ Name is using title case
✔ Has documentation URL set
✔ Has management URL set
✔ Has at least 1 field
✔ …
```
> Add Lacework plugin

- sdk/rpc/proto/protocol.go
- sdk/rpc/server/server.go
Related issue: https://github.com/1Password/shell-plugins/issues/90
The `Cache` and `CommandLine` field were left nil in the provision output response. This caused panics for both plugins using `Cache` and plugins using additional command flags.
Actually, the desired response of the RPC call should be the `ProvisionOutput` exactly as it was passed down from OP (as @Marton6 noted), but for a certain reason the fields of the pointer argument (`output`) of the call were nullified. (were brought to their zero values).
this MR:
- adds a `ProvisionOutput` field to the `ProvisionCredentialRequest`., and uses it as response of the RPC call
- adds functionality for catching a panic from a locally built plugin and outputting it before the OP panic is reached, so that the OP panic doesn't mask the …
> Fix local builds that use cache or additional command flags

- cmd/contrib/main.go
This PR adds tests for credential the default credential provisioner and credential importers when generating a new plugin using `make new-plugin`.
For testing, run `make new-plugin` two times. First, omit the credential example, second time, add it. The template should be able to gracefully handle both cases. 
I have a few open questions about wrapping up this MR, which I'll be adding in comments.
> Add template for credential importer and provisioner tests

- plugins/readme/api_key.go
- plugins/readme/api_key_test.go
- plugins/readme/plugin.go
- plugins/readme/rdme.go
- plugins/readme/test-fixtures/readme.json
Hi folks, [big 1Password fans](https://blog.readme.com/two-factor-auth/) over here at ReadMe! Looking forward to being a part of this exciting new ecosystem 💙
~I still have a few small outstanding TODOs in this PR (that I'll address before officially marking this as ready for review), but the main outstanding issue is that I'm running into is that the env variable `RDME_API_KEY` isn't properly being provisioned in my testing 😕 see #107 for more information!~
**EDIT**: fixed, thanks for your help @SimonBarendse @florisvdg!
Closes #108
> Add ReadMe plugin

- plugins/hcloud/api_token.go
- plugins/hcloud/api_token_test.go
- plugins/hcloud/hcloud.go
- plugins/hcloud/plugin.go
- plugins/hcloud/test-fixtures/hcloud.toml
Adds support for [hcloud](https://github.com/hetznercloud/cli) from [Hetzner](https://www.hetzner.com/de/) well known hosting provider in Germany also expanding to US right now
> hcloud: init plugin

- cmd/contrib/main.go
- cmd/contrib/main_test.go
This PR improves validation for `Credential Name` in a survey, when user runs `make new-plugin`. 
It also applies `Transform` function on user input. Therefore users are able to provide input in any case (upper, lower, camel etc.). 
`Validate` function checks that provided string is in TitleCase.
The user has to re-enter value/select from suggested if not passed. The error appears in a console in this case.
`Transfrom` function finds the corresponding value among defined credential names and returns it. Returns provided value otherwise.
> Survey credential name validation and transform improvments

- plugins/twilio/api_key.go
- plugins/twilio/api_key_test.go
- plugins/twilio/test-fixtures/config.json
This PR adds Twilio config file importer.
The config file is located `~/.twilio-cli/config.json`.
It can contain multiple profiles and each of them can be saved as a separate 1password item.
> Twilio config file importer

- README.md
We're super eager to help anyone wanting to start contributing. I've added a link to book a pairing session with one of our teammates and another mention of the Slack space where we're hanging out to help.
In addition, I've added a section on community & support, where I've added the Slack space, the newsletter and filing issues, so it's clear for folks visiting the README how they can get involved and stay up-to-date, if they so wish.
> Add more ways to get in contact for help

- plugins/cargo/api_token.go
- plugins/cargo/api_token_test.go
- plugins/cargo/cargo.go
- plugins/cargo/plugin.go
- plugins/cargo/test-fixtures/credentials.toml
Currently don't have the test passing for importing credentials from a file, working on that now.
If I change [registry] to [[registry]] it passes, but that's not how the file is created by cargo. 
Resolves #81
> Add support for cargo

- plugins/argocd/argocd.go
- plugins/argocd/auth_token.go
- plugins/argocd/auth_token_test.go
- plugins/argocd/plugin.go
- plugins/argocd/test-fixtures/config
This PR Adds support for Argo CD CLI and enables authentication using [environment variable](https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables/).
> Add ArgoCD support

- sdk/importer.go
- sdk/importer/helpers.go
- sdk/plugintest/importer_test_helper.go
```go
Importer: importer.TryAll(
importer.TryAllEnvVars(fieldname.Token, "EXAMPLE_ACCESS_TOKEN"),
importer.MacOnly(
TryExampleConfigFile("~/Library/Application Support/example/config.yml"),
),
importer.LinuxOnly(
TryExampleConfigFile("$XDG_CONFIG_HOME/example/config.yml"),
),
),
```
> Add importer helpers to support OS-specific importers

- plugins/databricks/databricks.go
- plugins/databricks/personal_access_token.go
- plugins/databricks/personal_access_token_test.go
- plugins/databricks/plugin.go
- plugins/databricks/test-fixtures/databrickscfg
This adds support for the [Databricks CLI](https://docs.databricks.com/dev-tools/cli/index.html). 
This CLI needs to know a "host" URL to the instance of Databricks you're working with, as well as your credentials that are specific to that instance. Personal access tokens are they primary way to authenticate, while username+password is possible but discouraged.
I've tested this on my own config, and both import and usage seems to work just fine 💯  Please let me know if you'd like to see more test cases or anything else before accepting. 
A couple notes: 
- I've opted for the "Person Access Token" credentials type, despite username+password being an option. The code here handles both cases, but the label of "Personal Access Token" isn't quite right in both cases. I still think it should be …
> add support for Databricks

- plugins/openai/api_key.go
- plugins/openai/api_key_test.go
- plugins/openai/openai.go
- plugins/openai/plugin.go
This PR adds a new plugin for the CLI in [OpenAI](https://openai.com/)'s Python [libary](https://pypi.org/project/openai/).
This CLI uses a single API Key environment variable, so the plugin simply provisions that.
- [Install the OpenAI CLI](https://pypi.org/project/openai/)
- [Create an OpenAI account](https://beta.openai.com/signup)
- From your account, [create a new API Key](https://beta.openai.com/account/api-keys)
- Either create a new vault item with this key, or manually create one during plugin init
- Checkout this branch: `git pull && git checkout jh/add-openai`
- Build the plugin `make openai/build`
- Init the plugin: `op plugin init openai`, source plugins
- If you haven't created a vault item, this is where you'll manually create one with you API Key
- Run a command, for …
> Add plugin for OpenAI CLI

- cmd/contrib/main.go
- plugins/aws/aws.go
- plugins/cargo/cargo.go
- plugins/circleci/circleci.go
- plugins/digitalocean/doctl.go
- plugins/fossa/fossa.go
- plugins/github/gh.go
- plugins/gitlab/glab.go
- plugins/heroku/heroku.go
- plugins/homebrew/brew.go
- plugins/okta/okta.go
- plugins/readme/api_key_test.go
- plugins/readme/rdme.go
- plugins/readme/rdme_test.go
- sdk/needsauth/helpers.go
- sdk/needsauth/helpers_test.go
- sdk/plugintest/importer_test_helper.go
- sdk/plugintest/needs_auth_test_helper.go
- sdk/plugintest/provisioner_test_helper.go
This PR makes the following improvements to the `needsauth` package and related functionality:
- Remove the ability from `needsauth` helper functions to specify multiple patterns in a single rule. This removes confusion, as seen in #107.
- Make the `--version` detection more strict, to only opt out of authentication if the version arg is the only arg present, to avoid false positives such as: `deploy --version 1.0.0`.
- Also consider `-V` for the version check.
- Add a `needsauth` helper to check for invocations with empty args, which often brings up the help text, so should not require authentication.
- Add this new empty-args helper to a bunch of plugins that follow this pattern.
- Add a test helper to the `plugintest` package to easily add test cases for `NeedsAuth` entries.
- Add …
> Improve needsauth helper package

- sdk/provisioner.go
- sdk/rpc/server/server.go
Panics happening in the shell plugins code called over rpc are no longer ignored. This makes for more useful debug messages in errors.
> RPC functions catch panics

- sdk/schema/fieldname/names.go
`APIKeyID` field name was introduced in PR https://github.com/1Password/shell-plugins/pull/95/ (Lacework plugin) but it seems that it wasn't added to the `ListAll` function in the field names SDK. This PR fixes it.
> Add APIKeyID field name to the ListAll function

- plugins/readme/rdme.go
- plugins/readme/rdme_test.go
Noticed an issue where 1Password prompts for authentication in the `rdme` CLI when the user passes in the `--key` argument, which shouldn't be happening. This PR fixes that!
This PR recreates the work I did in https://github.com/1Password/shell-plugins/pull/135.
> Don't auth for `--key` arg in ReadMe plugin

- plugins/sourcegraph/access_token.go
- plugins/sourcegraph/access_token_test.go
- plugins/sourcegraph/plugin.go
- plugins/sourcegraph/src.go
- sdk/schema/fieldname/names.go
This PR adds support for the Sourcegraph CLI. Fixes https://github.com/1Password/shell-plugins/issues/144.
Couple of notes:
- The CLI does not support config file imports. The CLI always expects the Sourcegraph instance host address and the access token to be set as environment variables.
- The `ManagementURL` isn't set for now because it's dynamic depending on the Sourcegraph instance host address **and** the username. In my case, it is https://sourcegraph.com/users/arun/settings/tokens. This case is similar to what happened with ReadMe, so based on [this advise](https://github.com/1Password/shell-plugins/pull/106#discussion_r1049357649) from @SimonBarendse, I haven't included `ManagementURL` field. When Shell Plugins support setting of dynamic `ManagementURL`s, we can update this …
> Add support for Sourcegraph

- sdk/rpc/proto/protocol.go
- sdk/rpc/server/server.go
RPC call responses are wrapping Provision, Deprovision and Import outputs, and are adding a Panic field meant to be set when panics arise in the RPC level. 
This is a better solution than https://github.com/1Password/shell-plugins/pull/121. It also requires protocol update to v4 hence it will get merged in `protocol-v4` to get shipped with more future similar changes.
This increases flexibility of handling these types of characteristic panics in the CLI.
See this dicussion for further details: https://github.com/1Password/shell-plugins/pull/121/files#r1055291768
> Create RPC function response structs which are wrapping sdk outputs

- cmd/contrib/main.go
This PR updates the field name on the `make new-plugin`-generated tests from `FieldName` to `FieldNameUpperCamelCase`, to avoid the breakage described below. In the below example, the correct field name should be "APIKey", not "API Key".
**Before:**
**After:**
> Fix Field Name case on the template-generated tests

- plugins/aws/access_key.go
Check if the environment has set this variable and if so, attempt the
import using that file.
Signed-off-by: Ismayil Mirzali <ismayilmirzeli@gmail.com>
> feat: check for AWS_SHARED_CREDENTIALS_FILE

- plugins/fastly/api_token.go
- plugins/fastly/api_token_test.go
- plugins/fastly/fastly.go
- plugins/fastly/plugin.go
- plugins/fastly/test-fixtures/config.toml
This PR adds support for [Fastly CLI](https://github.com/fastly/cli/). Fixes https://github.com/1Password/shell-plugins/issues/133.
- Fastly uses `API Token`s to authenticate.
- `FASTLY_API_TOKEN` envvar (environment variable) is the easiest way to authenticate. The CLI also supports `-t`, `--token` as command flags to login, but environment variables are preferred.
`fastly profile` command has a bunch of sub-commands `create`, `delete`, `list`, `switch`, `token` and `update`. Of these commands, except for `list` subcommand, all subcommands can be used in the form of the same environment variable (_I think_), but that's not possible just yet because Shell Plugins does not offer a simple way to switch to another credential:
- https://github.com/1Password/shell-plugins/issues/130
Until that …
> Add support for Fastly with envvar provisioning and config file imports

- sdk/provision/file_provisioner.go
Some CLIs only allow a config file path to be set using the directory it's in. This PR adds a variation to the existing `provision.SetPathAsEnvVar("FOO_CONFIG_FILE_PATH")` helper which lets you provision the output directory as an environment variable, which can be used like this: `provision.SetOutputDirAsEnvVar("FOO_CONFIG_DIR")`.
> Add file provisioner helper to provision output dir

- plugins/ngrok/credentials.go
- plugins/ngrok/credentials_test.go
- sdk/schema/credential_type.go
- sdk/schema/fieldname/names.go
Related PR: https://github.com/1Password/shell-plugins/pull/186
Add ability to specify various names for a `CredentialField`, so that users aren't constrained to map a field to only one name.
The order in which these names are specified matters towards which 1Password item field will be selected. 
Example:
A `CredentialField` with `Name` set to `d` and `AternativeNames` set to `[]sdk.FieldName{"b", "a", "c"}` and an item with fields named `a`, `b` and `c` will result into a `ProvisionInput` with `ItemFields` containing the value of `b`. If the item were to be added with a field `d` then the value in `ItemFields` would become that of field `d` since the `Name` takes priority over `AlternativeNames`.
For this to work in all cases, a constraint for all fields should be that they do not share …
> Add alternative field names

- plugins/homebrew/brew.go
This is a "smarter" wrapper around the `brew-bump-*` subcommands that auto-detects the latest version, checks for existing PRs, etc.
> Add `brew bump` sub-command to NeedsAuth list

- .github/workflows/test.yaml
Our lint step started to fail suddenly. This branch attempts to fix it.
https://github.com/1Password/shell-plugins/issues/195
> Fix PR pipeline linter

- plugins/sourcegraph/access_token.go
The [Sourcegraph](https://docs.sourcegraph.com) plugin currently _requires_ the endpoint field, but I'm not sure that's necessary because Sourcegraph also has a main API. 
@arunsathiya Was there a reason for this, or can we make it optional?
> Make Sourcegraph endpoint optional

- plugins/treasuredata/td.go
While the credential name within the Treasure Data plugin is `API Key`, the executable references `Access Key`. 
This MR fixes this issue.
> Add correct credential name to Treasure Data executable

- sdk/schema/plugin.go
- sdk/schema/validation.go
https://github.com/1Password/shell-plugins/pull/225 showed that currently, errors where undefined credentials can be referenced within the executable can happen.
This adds a validation check that will take place automatically, in the CI pipeline.
> Check that all executable credentials are defined in the plugin

- plugins/sourcegraph/access_token.go
In the dashboard the management URL is dynamic; It contains the username: https://sourcegraph.com/users/<username>/settings/token
That's probably why it wasn't included in the first iteration of this plugin.
I just found that https://sourcegraph.com/user/settings/tokens redirects to the management URL for the currently logged in user. Sourcegraph also uses this in the 'src login' command, so it should be safe to use that here as well.
> Add ManagementURL for Sourcegraph plugin

- plugins/gitea/personal_access_token.go
- plugins/gitea/personal_access_token_test.go
On macOS, `tea` writes its configuration to
`~/Library/Application Support/tea` and not `~/.config/tea`. This breaks the tea plugin. Go provides `os.UserConfigDir` to abstract the location of the config directory, so use that to fix macOS while not breaking Linux. In case `os.UserConfigDir` fails, fall back to `~/.config/tea` (this shouldn't happen unless something weird is going on, like the user's $HOME is not set.)
> fix(tea): use `os.UserConfigDir` to find config

- CONTRIBUTING.md
This PR adds a section about the documentation process for shell plugins to `contributing.md`.
> Add section about documentation to contributing.md

- Makefile
- cmd/contrib/scripts/config_dir_getter.go
- cmd/contrib/scripts/main.go
- go.mod
- go.sum
Currently, the config directory for shell plugins is hard-coded as `~/.op`. Whenever a user builds a plugin (e.g. `make aws/build`), the plugin executable gets stored at `~/.op/plugins/local`. However, depending on the user's environment, `~/.op` will not always necessarily be the config directory that's used by the CLI. The [CLI documentation](https://developer.1password.com/docs/cli/config-directories/) lists the order of precedence for possible configuration directory locations. We should search for an existing config directory based on that order of precedence and use it if it exists, for the sake of consistency and to avoid situations where multiple config directories get created for users of the CLI that also build their own shell plugins, which could result in issues like this …
> Search alternative config directories when building a plugin

- plugins/registry_test.go
- sdk/names.go
- sdk/schema/credential_type.go
- sdk/schema/credname/names_test.go
- sdk/schema/plugin.go
- sdk/schema/validation.go
- sdk/schema/validation_test.go
We need a way to identify credentials in a stable long-term manner. The credential names could be subject to change at a certain point in the future, so we are introducing an additional layer meant for unique identification that is not vulnerable to sdk changes.
Also we need to enforce that plugins are uniquely identified by their name, and credentials inside each plugin definition are uniquely identifiable by their ID.
* Resolves: #257 
Relates other some internal issues.
Credentials now have an ID they can be identified after.
Plugins can be uniquely identified by their name, and credentials inside a plugin definition can be uniquely identified by their ID
> Add IDs to credentials based on their name

- plugins/github/gh.go
Do not require auth if running `gh __complete` for shell completion.
> gh: do not require auth if running for shell completion

- cmd/contrib/main.go
Don't require plugins to have executables.
Since the Terraform plugin can consume credentials of other plugins, there is now a use-case for plugins with no executables. 
If a service offers a Terraform provider, but no CLI, Shell Plugins should still offer a solution to allow for the provisioning of that credential.
In this situation, simply not providing an executable in the creation wizard does the trick.
`make new-plugin` and leave the "Executable" prompt empty. The wizard should still work.
> Don't require plugins to have executables

- go.mod
- go.sum
- plugins/ngrok/credentials.go
- plugins/ngrok/credentials_test.go
- plugins/ngrok/env_var_provisioner.go
- plugins/ngrok/ngrok.go
- plugins/ngrok/provisioner.go
Fixes https://github.com/1Password/shell-plugins/issues/216 and fixes https://github.com/1Password/shell-plugins/issues/274
This PR updates the ngrok Shell Plugin to use environment variables to provision credentials when the ngrok CLI is 3.2.1 or higher. We'd retain the config file-based provisioner for older versions.
- Make sure there isn't a ngrok config file on your computer at [the path depending on your OS](https://ngrok.com/docs/ngrok-agent/config/#default-locations). (This is important because as of https://github.com/1Password/shell-plugins/pull/194, we detect such configuration files and merge with 1Password-generated configuration file)
- Check ngrok version by running `ngrok --version`. If it's 3.2.1 or higher, any `ngrok api` command (example `ngrok api tunnels list`) should …
> update(ngrok): switch to envvars provisioner for ngrok 3.2.1 and higher

- plugins/ngrok/credentials.go
- plugins/ngrok/credentials_test.go
- plugins/ngrok/test-fixtures/config.yml
Resolves: #249 
The lengths of the ngrok credentials specified in ngrok/credentials.go seem to be incorrect. The correct lengths should be:
- Authtoken: 49
- API key: 49
You can create the secrets using these links:
- https://dashboard.ngrok.com/get-started/your-authtoken
- https://dashboard.ngrok.com/api
The incorrect length values don't seem to affect any functionality at the moment, but it's important to record the correct values for future features, e.g. any case where validating extracted credentials is needed.
> Correct ngrok credential lengths

- plugins/aws/importers.go
It seems the aws-vault importer is creating the `.aws/config` file if it doesn't exist. We should make sure that importers only read.
`op plugin init aws` and import credentials
AWS Shell Plugin importer never creates a `.aws/config` file if one does not exist already.
> Don't write a new aws config file when importing

- .github/workflows/pr-check-signed-commits.yml
Adds a GitHub Actions workflow on PRs to ensure all commits are signed, using the [check-signed-commits-action](https://github.com/1Password/check-signed-commits-action).
Fork the repo and create a PR with an unsigned commit. The check should fail and you should see a comment on the PR.
N/A
> Add GitHub Actions workflow to check signed commits

- plugins/vercel/api_token.go
- plugins/vercel/api_token_test.go
- plugins/vercel/plugin.go
- plugins/vercel/test-fixtures/auth.json
- plugins/vercel/vercel.go
Add `vercel` plugin.
```
op plugin init vercel
op plugin run -- vercel whoami
```
> feat: add vercel plugin

- plugins/aws/importers.go
A bug was introduced in this PR, which was uncovered through circumstantial testing. It is reproducible by initialising the aws plugin and importing.
remove the `[default]` section from your `.aws/config` and run `op plugin init aws` & select `Import` option
> Fix AWS importer nil pointer panic

- plugins/aws/access_key_test.go
- plugins/aws/sts_provisioner.go
This change makes so that having `source_profile` in your `.aws/config` file doesn't error out and instead behaves as expected.
**This is the expected behaviour:**
1. Case 1: Only `source_profile` is specified in a profile. --> The source profile is inspected recursively and the right credentials provider is chosen to be used for the current profile. 
2. Case 2: `source_profile` is specified, alongside other role/mfa specific information (`role_arn`. `mfa_serial` etc) --> the source profile is inspected recursively to determine the right provider. This provider is then used as "base" credentials for executing SDK calls to the STS service for retrieving another set of temporary credentials as marked by the other role/mfa specific information present in the current profile.
**Further …
> AWS: Support source_profile

- plugins/aws/sts_provisioner.go
- plugins/aws/utils.go
When any `aws` command is run, the shell plugin currently outputs some additional logs related to the config file reader/importer. With the changes proposed on this PR, we'd hide those logs for now, but a long-term effort would be to identify why those logs are appearing and not printing them in the first place.
I have used the same solution that @williamhpark [outlined on the issue](https://github.com/1Password/shell-plugins/issues/254).
* Resolves: https://github.com/1Password/shell-plugins/issues/254
- Clone this branch
- Run `make aws/build`
- Set up AWS shell plugin with `op plugin init aws`
- Run any AWS command, like `aws s3 ls`
- Make sure that no additional logs appear before the `aws s3 ls`'s output appears.
Here's how it looks for me with the proposed changes:
Silence AWS …
> Silence logs generated by aws-vault on the AWS shell plugin

- cmd/contrib/main.go
When generating a plugin using executable name which is in kebab-case, the plugin's go file name would be in snake_case
* Resolves: #287
1. Run `make new-plugin`
2. Give the executable name as `redis-cli`
3. Resulting plugin will have the file name as redis_cli.go
When generating a plugin using executable name which is in kebab-case, the plugin's go file name would be in snake_case
> fix: generated plugin file name should be snake_case

- .github/workflows/pr-check-signed-commits.yml
Follow-up to https://github.com/1Password/shell-plugins/pull/289
Currently, the commit signing check on PRs doesn't show the PR comment if the PR author is external.
This is because the passed in `GITHUB_TOKEN` does not have write access to the PR.
For more info about the problem and the solution, see [this write-up on the `actions/labeler` repo](https://github.com/actions/labeler#permissions) which has the same problem.
1. Create shell-plugins fork on personal namespace
2. Create a PR from a different account that does not have write access to the fork
N/A
> Allow commit signing PR comment on fork PRs

- .gitignore
- Makefile
- cmd/contrib/main.go
- plugins/registry.go
- sdk/schema/plugin.go
This PR adds a `make registry.json` command, generating a json-formatted registry.
For the time being, this will be used as configuration for the Shell Plugins banners that OPH renders for Shell Plugins items. However, this can also serve as boilerplate for more complex configuration that can be built on top of this repo.
Run `make registry.json`
> Add `make registry.json` command 

- plugins/postgresql/pg_dump.go
- plugins/postgresql/pg_restore.go
- plugins/postgresql/plugin.go
Adds support for `pg_dump` and `pg_restore` utilities for PostgreSQL.
* Resolves: #
* Relates: #
The PostgreSQL plugin now also supports the `pg_dump` and `pg_restore` CLI utilities.
> update(postgresql): add support for 'pg_dump' & 'pg_restore'

- plugins/pipedream/api_key.go
- plugins/pipedream/api_key_test.go
- plugins/pipedream/pd.go
- plugins/pipedream/plugin.go
- plugins/pipedream/test-fixtures/config
- plugins/pipedream/test-fixtures/import
- plugins/pipedream/test-fixtures/provision
- sdk/schema/fieldname/names.go
Add support for Pipedream CLI. The shell plugin provisions a configuration file at `~/.config/pipedream/config`. The shell plugin also imports the API Key and the Org ID from the same file at the same path, if they exist.
* Resolves: #
* Relates: #
- Install Pipedream CLI and set up the shell plugin.
- If the config file exists at `~/.config/pipedream/config`, the first time `op plugin init pd` is run, the API Key and Org ID can be imported into 1Password.
- Test with `pd login status`. It should show that the login is successful.
Add support for Pipedream CLI
> Add support for Pipedream CLI

- plugins/kaggle/api_token.go
- plugins/kaggle/api_token_test.go
- plugins/kaggle/kaggle.go
- plugins/kaggle/plugin.go
- plugins/kaggle/test-fixtures/config.json
Add support for Kaggle CLI. Kaggle CLI supports environment variables KAGGLE_KEY and KAGGLE_USERNAME
* Resolves: #
* Relates: #
- Install [Kaggle CLI](https://github.com/Kaggle/kaggle-api) and set up shell plugin.
- Run `op plugin init kaggle` to configure username and [Kaggle API Key](https://www.kaggle.com/settings/account).
- Future queries should use these credentials.
Add support for Kaggle.
> Add support for Kaggle CLI

- plugins/crowdin/access_token.go
- plugins/crowdin/access_token_test.go
- plugins/crowdin/crowdin.go
- plugins/crowdin/plugin.go
- sdk/schema/fieldname/names.go
Add support for the [Crowdin CLI](https://crowdin.github.io/crowdin-cli/)
* Resolves: #
* Relates: #
When inside of a Crowdin project with a `crowdin.yml` file, run a command such as `crowdin list branches`
Authenticate the Crowdin CLI using Touch ID and other unlock options with 1Password Shell Plugins.
The Crowdin plugin can be initialized with a Crowdin Personal Token, an optional Project ID, and a Base URL (for Crowdin Enterprise) using `op plugin init crowdin`. Please see the [Crowdin documentation](https://developer.crowdin.com/configuration-file/#api-credentials-from-environment-variables) to ensure your project is set up to authenticate via environment variables.
> Add support for Crowdin CLI

- plugins/sentry/auth_token.go
- plugins/sentry/auth_token_test.go
- sdk/schema/fieldname/names.go
Added configuration for `SENTRY_PROJECT` & `SENTRY_URL` env vars. [[Docs]](https://docs.sentry.io/product/cli/configuration/?original_referrer=https://docs.sentry.io/platforms/javascript/guides/nextjs/sourcemaps/#configuration-values)
* Resolves: #
* Relates: #
Run `sentry-cli info`. The configured values for `SENTRY_PROJECT` & `SENTRY_URL` should show:
```zsh
Sentry Server: https://sentry.io
Default Organization: acme
Default Project: example
Authentication Info:
Method: Auth Token
User: user@example.com
Scopes:
- event:admin
- event:read
- member:read
- org:read
- project:read
- project:releases
- team:read
```
Added support for `SENTRY_PROJECT` & `SENTRY_URL`.
> feat(sentry): add `SENTRY_PROJECT` & `SENTRY_URL`

- plugins/todoist/api_token.go
- plugins/todoist/api_token_test.go
- plugins/todoist/plugin.go
- plugins/todoist/test-fixtures/config.json
- plugins/todoist/todoist.go
Add support for Todoist CLI. The shell plugin provisions a configuration file at `~/.config/todoist/config.json`. The shell plugin also imports the Todoist token from the same file at the same path, if it exists.
* Resolves: #
* Relates: #
- Install Todoist CLI and set up shell plugin.
- Run `op plugin init todoist` to import the token from `~/.config/todoist/config.json`
- The next time `todoist` commands are run, the shell plugin provisions the token to the same file path.
Add support for Todoist CLI.
> Add support for Todoist CLI

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
We now have a Slack invitation link for the developer Slack on a domain we control. This PR updates the links:
- Old link: https://join.slack.com/t/1password-devs/shared_invite/zt-1z0rd7lro-fx4LPkQwUF89~PzpDGPe1A
- New link: https://developer.1password.com/joinslack
- Visit the new link
- See that it offers a sign up flow and verify that any domain can be used for the sign up.
Update developer Slack invitation link to the one we control
> Update developer Slack invitation link to the one we control

- plugins/localstack/api_key.go
- plugins/localstack/api_key_test.go
- plugins/localstack/localstack.go
- plugins/localstack/plugin.go
LocalStack is ["a fully functional local cloud stack, to develop and test your cloud and serverless apps offline".](https://localstack.cloud/).
This PR adds support for setting the API key for use with LocalStack's pro offering.
*Disclaimer: I work for LocalStack*
```
localstack start
```
> Add LocalStack plugin

- plugins/axiom/axiom.go
- plugins/axiom/personal_access_token.go
- plugins/axiom/personal_access_token_test.go
- plugins/axiom/plugin.go
- sdk/schema/fieldname/names.go
Add support for Axiom CLI. The CLI has support for environment variable AXIOM_TOKEN which can be used for authentication.
* Resolves: #
* Relates: #
- Install Axiom CLI and set up shell plugin.
- Run `op plugin init axiom`
- Future queries should set AXIOM_TOKEN and use it for authentication.
Add support for Axiom CLI.
> Add support for Axiom CLI

- plugins/cachix/auth_token.go
- plugins/cachix/auth_token_test.go
- plugins/cachix/test-fixtures/cachix.dhall
Adds a file importer for the Cachix plugin. The file is stored at `~/.config/cachix/cachix.dhall` and is generated from a terminal command. To avoid bringing in a third-party dependency, the file contents are processed as a string, rather than using a dhall parser.
* Resolves: #111 
When running `op plugin init cachix`, you should now see the option to import credentials using the specified file.
The Cachix plugin now checks for the `~/.config/cachix/cachix.dhall` file and attempts to import an auth token using the specified file.
> Add file importer for cachix plugin

- plugins/terraform/terraform.go
Terraform init command also requries authentication to be able to authenticate backend in certain cases, for example, using s3 as a backend for Terraform.
* Resolves: [#372](https://github.com/1Password/shell-plugins/issues/372)
* Relates: #
terraform init
Adding init to the commands that need authentication
> Adding init command

- cmd/contrib/main.go
- cmd/contrib/main_test.go
Prior to this change, when the credential name's last word is larger than seven characters, the field name generated by the "make new-plugin" template is empty. 
With this change, the last word of the credential name is set as the field name. In the example below, field name `Credentials` is generated for the credential name `GitHub Access Credentials`.
If the last word is smaller than seven characters, the usual pattern of stitching together the last several words of the credential name (proposed originally on this PR https://github.com/1Password/shell-plugins/pull/72) will be retained. In the example below, field name `API Key` is generated for the credential name `GitHub API Key`.
* Resolves: https://github.com/1Password/shell-plugins/issues/164
- Clone this branch and switch to it.
- …
> fix(new-plugin): Set only the last word of the credential name as the field name, if it's larger than seven characters

- .github/workflows/pr-check-signed-commits.yml
The job was previously ran on "pull_request_target". This runs the job on the base branch (i.e. the `main` branch of the
1password/shell-plugins repo). Since we want to know if commits are signed on all the commits to be merged (i.e. also on the fork), I have changed this job to run on the merge commit instead.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
Note that the usage example of https://github.com/1Password/check-signed-commits-action also recommends running on the "pull_reqeusts" event.
See https://github.com/1Password/shell-plugins/pull/332 where we run into this in practice. The job is passed, but commits aren't signed.
> Fix signed commits CI job

- plugins/postgresql/pgcli.go
- plugins/postgresql/plugin.go
Add support support for `pgcli` as alternative cli client for PostgreSQL.
Pgcli is a rich, postgres client with syntax highlighting, smart completion and multiline support.
More info about pgcli: https://www.pgcli.com/
Since pgcli can use the same environment variables as psql it can be used as a psql replacement:
```shell
op plugin run -- pgcli
```
or we can configure it if psql is not already configured:
```shell
op plugin init pgcli
```
PostgreSQL plugin now also supports `pgcli` as an alternative to psql.
> update(postgresql): add support for 'pgcli'

- plugins/yugabytedb/database_credentials.go
- plugins/yugabytedb/database_credentials_test.go
- plugins/yugabytedb/plugin.go
- plugins/yugabytedb/ysqlsh.go
Added Yugabyte Shell Plugin Similar to Postgres
> Added Shell Plugin for Yugabyte

- .github/workflows/test.yaml
- Makefile
You can now check if your code passes the lint rules by running `make lint` locally.
1. Run `make lint`.
2. That's it :tada:
This is an internal change (i.e. not to be included in CLI release notes).
Change: You can now check if your code passes the lint rules by running `make lint` locally.
> Add job to locally lint changes before pushing to remote

- .github/workflows/check-flake.yml
- .github/workflows/update-flake-dependencies.yml
Updates the `check-flake` CI job to run on PRs that change any `*.nix` files or `flake.lock`, also adds @AndyTitu as a default reviewer for the automated `flake.lock` update PRs.
* Resolves: #
* Relates: #
Let's merge this before #445, then merge main into #445 and make sure CI runs there
Run `check-flake` CI job on PRs where any `*.nix` files or `flake.lock` are changed
> fix(ci): Run `check-flake` on Pull Requests

- .github/workflows/approve-flake-lock-prs.yml
- .github/workflows/update-flake-dependencies.yml
Makes the `github-actions[bot]` automatically approve its own automated `flake.lock` update PRs. The PRs will still require 1 manual human approval, but only requiring 1 human approval helps us keep up with it, and there is reduced risk with these PRs vs. dependabot PRs for example, since we're only pulling in `flake-utils` and `nixpkgs` which are already screened by their respective maintainers.
* Resolves: #452 
TODO I'm not sure how exactly to test this other than merging it to main and running a new flake.lock automation job to see if this applies correctly to it. @AndyTitu any ideas?
Update flake.lock automation to reduce maintenance burden.
> chore(ci): Auto-add one approval to automated flake.lock PRs

- .github/workflows/approve-flake-lock-prs.yml
Fixes CI automation for `flake.lock` updates to actually run the job on PRs (hopefully 🤞)
Fix flake.lock CI automation definitions to run the job on automated flake.lock PRs
> fix(ci): Run automated PR approval on `pull_request:` instead of `pull_request_target:`

- plugins/aws/cdk.go
Fixes the _cdk_ plugin not handling the `--profile` flag correctly when a profile is using role assumption. Now it matches  the expected behavior of the _aws_ plugin's `--profile` flag and the `AWS_PROFILE` environment variable.
If you have an existing CDK stack, you can confirm that using a profile to assume a role used for deployments.
```shell
cd $YOUR_CDK_DIR
cdk diff --profile cdk-stack-admin
```
Example `~/.aws/config` file. Swap out with names and numbers from your account
```ini
[default]
[profile cdk-stack-admin]
source_profile=default
role_arn=arn:aws:iam::<AWS_ACC_NUM>:role/<CDK_ADMIN_ROLE>
role_session_name=cdk-stack-admin
```
Without the patch, the _cdk_ will encounter the error below and fail
```
Need to perform AWS calls for account <AWS_ACC_NUM>, but no credentials have …
```
> cdk.go: support --profile flag by adding missing provisioner

- plugins/scaleway/access_key.go
- plugins/scaleway/access_key_test.go
- plugins/scaleway/plugin.go
- plugins/scaleway/scw.go
- plugins/scaleway/test-fixtures/config
- sdk/schema/fieldname/names.go
Plugin for the CLI from the cloud provider [Scaleway](https://www.scaleway.com/en/). Only supports default configuration (not the use of profiles).
* Register an account at [Scaleway](https://www.scaleway.com) and create an API key.
* Install the [Scaleway CLI](https://www.scaleway.com/en/cli/)
* `scw init`
* `op plugin init scw`
* `scw account project list`
New plugin for the Scaleway CLI
> Scaleway plugin

- nix/shell-plugins.nix
1Password CLI requires setting the group of the executable to `onepassword-cli`. This isn't possible when home-manager is installed in standalone mode (e.g. Ubuntu or other distributions). Opting out of installing the 1Password CLI
with nix allows using the system-wide installation (e.g. via apt).
This change also allows changing the package. It's beneficial when nixpkgs-unstable is mapped to `pkgs.unstable` via an overlay.
This is **not** breaking, the current behavior remains as is.
Improved experience for nix users.
Opting out of installing the package:
```nix
{
imports = [ inputs._1password-shell-plugins.hmModules.default ];
programs._1password-shell-plugins = {
enable = true;
package = null;
plugins = with pkgs; [ gh awscli2 cachix ];
};
}
```
Changing the package:
```nix
{
imports = …
```
> Optional package

- .github/workflows/update-flake-dependencies.yml
Fixes the nix flake update job to skip trying to create a PR if one already exists.
Green CI
Fix Nix Flake Update CI job to skip creating a PR if one already exists
> fix(ci): Don't try to create a PR if one already exists

- nix/shell-plugins.nix
Fixes a warning that `_1password` has been renamed to `_1password-cli`
* Resolves: #527
Green CI
Update Nix package derivation to resolve warning about renamed package.
> fix(nix): Resolve warning about 1Password nixpkgs name

- flake.lock
- flake.nix
This change removes the dependency on `flake-utils` and replaces it with `nix-systems`.  
It introduces a `forAllSystems` helper based on `nixpkgs.lib.genAttrs` to generate development shells for all supported systems.  
The overall structure of the flake remains the same, but the dependency graph is simplified and more explicit.
* Resolves: #
* Relates: #
1. Run `nix develop` on any supported system.  
2. Confirm that a development shell is created with the Go toolchain (`go`, `gopls`).  
3. Validate that `nixosModules` and `hmModules` can still be imported as before.  
Replaced `flake-utils` with `nix-systems` and refactored flake outputs to generate development shells for all supported systems.
> refactor(flake): replace flake-utils with nix-systems
